### ISSUE TITLE
require path for controllers in routes is invalid

### ISSUE THREAD

**Issue by tzwm** [tjulinfan/cppwebsite#1]
I found the require path for controllers in routes is not a relative path. So I can't run the server.

Example in routes/page.js:
`var studentController = require('cppwebsite/controllers/studentController');`

**Comment by tjulinfan** [comment]
you need run 'npm run cppwebsite' at linux environment...


2015-05-03 23:11 GMT+08:00 Samwise Wang <notifications@github.com>:

**Comment by tzwm** [comment]
@tjulinfan Got it.
